### ISSUE TITLE
erratic filter behaviour

### ISSUE THREAD

**Issue by mikailweston** [KullmannLab/pyecog2#15]
high pass filter does not apply properly over 50Hz
[filter bug.pptx](https://github.com/KullmannLab/pyecog2/files/5911345/filter.bug.pptx)

**Comment by mfpleite** [comment]
Are you in the up to date with Development_ML?
The plots you show look outdated. In my latest tests the plots look substantially better.
However, the filters will never be perfect when the plotted data is down sampled to a point where the Nyquist frequency is bellow the frequency cutoffs. I am filtering the plotted data, instead of the original data, so that we can quickly process at least approximately overviews of large datasets. However if you zoom in the filters will be applied precisely.
![Screenshot from 2021-02-02 14-44-33](https://user-images.githubusercontent.com/13346236/106608890-39c13e00-6565-11eb-8751-1407d465f08a.png)
