### ISSUE TITLE
NP data timescale for overview

### ISSUE THREAD

**Issue by mikailweston** [KullmannLab/pyecog2#3]
X axis is date and time of recording, not duration of current recording.

Bug allows x axis to extend beyond current recording. If you accidentally scroll past the start or end, it can be difficult to go back to start of file without closing it and reopening.

**Comment by mfpleite** [comment]
This was made by design, because usually people will want to scroll seamlessly through several contiguous files. I have made a small change to make sure you can't scroll past the start or end of the whole dateset. 
To recenter on a particular file, you can click on the file name on the file tree and it should take you to the start of that file.

The date on the X axis is also a design choice. I can make the axis of the inset (bottom) plot to be time relative to start of file if that is a desirable feature.

**Comment by mikailweston** [comment]
Ok, sounds good. I can work with that
